# Generated by Django 5.0.6 on 2024-06-18 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=30)),
                ('task_description', models.CharField(max_length=50, null=True)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('task_completion_counter', models.IntegerField(default=0, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidequest.user')),
            ],
        ),
    ]
