# Generated by Django 5.0.6 on 2024-06-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
