# Generated by Django 5.0.6 on 2024-07-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidequest', '0006_character_attacks_alter_character_charisma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_name',
            field=models.CharField(default='barbarian', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('human', 'Human')], default='human', max_length=100),
        ),
    ]
