# Generated by Django 5.0.6 on 2024-07-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidequest', '0007_alter_character_class_name_alter_character_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_name',
            field=models.CharField(choices=[('barbarian', 'Barbarian')], default='barbarian', max_length=100),
        ),
    ]
