# Generated by Django 5.0.6 on 2024-07-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidequest', '0009_rename_user_id_character_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_name',
            field=models.CharField(default='barbarian', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(default='human', max_length=100),
        ),
    ]
