# Generated by Django 5.0.6 on 2024-07-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidequest', '0012_monster_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=100),
        ),
    ]
