# Generated by Django 5.0.6 on 2024-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidequest', '0013_character_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
